crypto: lz4: Fix undeclared error in lz4_compress_crypto
After commit fd400fc (BACKPORT: crypto: change LZ4 modules to work with new LZ4 module version),
this build error appears:

../crypto/lz4.c: In function ‘lz4_compress_crypto’:
../crypto/lz4.c:52:16: error: ‘ctx’ undeclared (first use in this function)
   slen, *dlen, ctx);
                ^~~

Signed-off-by: crian <crian84@gmail.com>